# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-24 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuoye02', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
