# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-23 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='look_books',
            fields=[
                ('序号', models.AutoField(primary_key=True, serialize=False)),
                ('书籍名称', models.CharField(max_length=32)),
                ('书籍价格', models.FloatField()),
                ('出版时间', models.DateField()),
                ('出版社', models.CharField(max_length=32)),
            ],
        ),
    ]
