# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-23 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zuoye01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='look_books',
            new_name='look_book',
        ),
    ]
