# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-23 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuoye01', '0002_auto_20190523_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='look_books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=32)),
                ('bprice', models.FloatField()),
                ('publication_date', models.DateField()),
                ('publishing_house', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='look_book',
        ),
    ]
